#application.yml

server:
  port: 8081

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/pyo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
      host: smtp.163.com #发送邮件服务器
      username: migukoo@163.com #发送邮件的邮箱地址
      password: SYYMRNDFNDTZVYYF #客户端授权码，不是邮箱密码,网易的是自己设置的
      properties.mail.smtp.port: 994 #465或者994
      from: migukoo@163.com # 发送邮件的地址，和上面username一致
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
